spring:
  data:
    mongodb:
      username: umut
      password: umut
      additional-hosts: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090