spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: umut
    password: umut
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/customers
    product-url: http://localhost:8222/api/products
    payment-url: http://localhost:8222/api/payments